
import java.io.*;
import com.opencsv.CSVWriter;
import com.opencsv.CSVReader;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */
public class frmAltadeProductos extends javax.swing.JFrame {
frmPrincipal datosdelafrmPrincipal = new frmPrincipal();
DefaultTableModel tabla = new DefaultTableModel();
public static String []Buscado = new String [4];

    /**
     * Creates new form frmAltadeProductos
     */
    public frmAltadeProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
         String []titulo = new String[]{"ID","Producto","Precio","Existencia"};
        tabla.setColumnIdentifiers(titulo);
        jTable.setModel(tabla);
        tabla.addRow(new Object[]{"To1","Toalla",datosdelafrmPrincipal.toalla,datosdelafrmPrincipal.ntoallas});
        tabla.addRow(new Object[]{"Pa2","Pastilla",datosdelafrmPrincipal.pastilla,datosdelafrmPrincipal.npastilla});
        tabla.addRow(new Object[]{"Ta3","Tampon",datosdelafrmPrincipal.tampon,datosdelafrmPrincipal.ntapones});
        tabla.addRow(new Object[]{"Pa4","Parche",datosdelafrmPrincipal.parche,datosdelafrmPrincipal.nparches});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAceptar3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar1.setBackground(new java.awt.Color(204, 204, 0));
        btnAgregar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregar1.setText("Buscar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        txtBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 180, -1));

        btnOrdenar.setBackground(new java.awt.Color(102, 102, 255));
        btnOrdenar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnOrdenar.setText("Ordenamiento");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        btnCSV.setBackground(new java.awt.Color(0, 102, 0));
        btnCSV.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnCSV.setText("Guardar en archivo CSV");
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });
        jPanel1.add(btnCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 204));
        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 70, 20));

        btnAceptar3.setBackground(new java.awt.Color(102, 102, 255));
        btnAceptar3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptar3.setText("Atras");
        btnAceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 80, 20));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setText("ALTA DE PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 900, 10));

        jTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 810, 120));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoverde.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:}
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar3ActionPerformed
        // TODO add your handling code here:
        frmSeleccion verfrmSeleccion = new frmSeleccion();
        verfrmSeleccion.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAceptar3ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String [] Datos = {"Ingrese el ID del producto","Ingrese el nombre de producto","Ingrese el Precio del producto","Ingrese la existencia del producto"};
        tabla.addRow(new Object[]{JOptionPane.showInputDialog(null,Datos[0]),
            JOptionPane.showInputDialog(null,Datos[1]),
            JOptionPane.showInputDialog(null,Datos[2]),
            JOptionPane.showInputDialog(null,Datos[3])});

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTable.getSelectedRow();
        tabla.removeRow(fila);
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
         try {

            // escribiendo datos

            String encabezado []  = {"ID", "Nombre del Producto "
                    , "Precio del Producto","Existencia "};
            String Toallas []  = {"To1","Toallla","10",datosdelafrmPrincipal.ntoallas+""};
            String Pastillas []  = {"Pa2","Pastilla","15",datosdelafrmPrincipal.npastilla+""};
            String Tampones []  = {"Ta3","Tampon","12",datosdelafrmPrincipal.ntapones+""};
            String Parches []  = {"Pa4","Parche","18",datosdelafrmPrincipal.nparches+""};
            String archCSV2 = ".\\InventarioD.csv";
            CSVWriter writer = new CSVWriter(new FileWriter(archCSV2));
            writer.writeNext(encabezado);
            writer.writeNext(Toallas);
            writer.writeNext(Pastillas);
            writer.writeNext(Tampones);
            writer.writeNext(Parches);
            writer.close();
            System.out.println("se escribieron los datos");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCSVActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
       frmOrdenamiento verfrmOrdenamiento = new frmOrdenamiento();
       verfrmOrdenamiento.setVisible(true);
        
           
       
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
         String [][] Datos =new String [4][4];
        Datos[0][0]="To1";Datos[0][1]="Toalla";Datos[0][2]="10";Datos[0][3]=""+datosdelafrmPrincipal.ntoallas;
        Datos[1][0]="Pa2";Datos[1][1]="Pastilla";Datos[1][2]="15";Datos[1][3]=""+datosdelafrmPrincipal.npastilla;
        Datos[2][0]="Ta3";Datos[2][1]="Tampon";Datos[2][2]="12";Datos[2][3]=""+datosdelafrmPrincipal.ntapones;
        Datos[3][0]="Pa4";Datos[3][1]="Parche";Datos[3][2]="18";Datos[3][3]=""+datosdelafrmPrincipal.nparches;
        if (txtBusqueda.getText().equals("To1")||txtBusqueda.getText().equals("Toalla")||txtBusqueda.getText().equals("to1")||txtBusqueda.getText().equals("toalla")||txtBusqueda.getText().equals("10"))
        {
            for (int i=0;i<4;i++)
            {
                Buscado[i]=Datos[0][i];
          
            }
            frmBuscado verfrmBuscado= new frmBuscado();
           verfrmBuscado.setVisible(true); 
           txtBusqueda.setText(null);
        }
         if (txtBusqueda.getText().equals("Pa2")||txtBusqueda.getText().equals("Pastilla")||txtBusqueda.getText().equals("pa2")||txtBusqueda.getText().equals("pastilla")||txtBusqueda.getText().equals("15"))
        {
            for (int i=0;i<4;i++)
            {
                Buscado[i]=Datos[1][i];
                
            }
             frmBuscado verfrmBuscado= new frmBuscado();
           verfrmBuscado.setVisible(true);
           txtBusqueda.setText(null);
        }
          if (txtBusqueda.getText().equals("Ta3")||txtBusqueda.getText().equals("Tampon")||txtBusqueda.getText().equals("ta3")||txtBusqueda.getText().equals("tampon")||txtBusqueda.getText().equals("12"))
        {
            for (int i=0;i<4;i++)
            {
                Buscado[i]=Datos[2][i];
                
            }
             frmBuscado verfrmBuscado= new frmBuscado();
           verfrmBuscado.setVisible(true);
           txtBusqueda.setText(null);
        }
           if (txtBusqueda.getText().equals("Pa4")||txtBusqueda.getText().equals("Parche")||txtBusqueda.getText().equals("pa4")||txtBusqueda.getText().equals("parche")||txtBusqueda.getText().equals("18"))
        {
            for (int i=0;i<4;i++)
            {
                Buscado[i]=Datos[3][i];
                
            }
             frmBuscado verfrmBuscado= new frmBuscado();
           verfrmBuscado.setVisible(true);
           txtBusqueda.setText(null);
        }
           //if(txtBusqueda.getText()!="To1"||txtBusqueda.getText()!="to1"||txtBusqueda.getText()!="Toalla"||txtBusqueda.getText()!="toalla"||txtBusqueda.getText()!="10"||
                //   txtBusqueda.getText()!="Pa2"||txtBusqueda.getText()!="pa2"||txtBusqueda.getText()!="Pastilla"||txtBusqueda.getText()!="pastilla"||txtBusqueda.getText()!="15"||
                //   txtBusqueda.getText()!="Ta3"||txtBusqueda.getText()!="ta3"||txtBusqueda.getText()!="Tampon"||txtBusqueda.getText()!="tampon"||txtBusqueda.getText()!="12"||
                //   txtBusqueda.getText()!="Pa4"||txtBusqueda.getText()!="pa4"||txtBusqueda.getText()!="Parche"||txtBusqueda.getText()!="parche"||txtBusqueda.getText()!="18")
          // {
          //     JOptionPane.showMessageDialog(null,"Fallo en la busqueda \n"
             //          + "por favor introduzca\n"+"un valor de busqueda valido"
             //          , null, 2, null); 
        //   }
              
           
           
           
        
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAltadeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAltadeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAltadeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAltadeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAltadeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAceptar3;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
