
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */
public class frmInventario extends javax.swing.JFrame {
        String NombreP,TipoP,MarcaP,TamañoP,MaterialP,datosSQL="";
        int PrecioP;
        conexionMysql objMysql= new conexionMysql();
        
    /**
     * Creates new form frmInventario
     */
    public frmInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        datosSQL=objMysql.MostrarSQL();
        txaMuestreo.setText(datosSQL);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        lblMaterial_P = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTipo_P = new javax.swing.JLabel();
        lblNombre_p = new javax.swing.JLabel();
        lblMarca_P = new javax.swing.JLabel();
        lblPrecio_P = new javax.swing.JLabel();
        lblTamaño_P = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMuestreo = new javax.swing.JTextArea();
        btnAlta = new javax.swing.JButton();
        btnAceptar3 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ALTA PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Insertar ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        lblMaterial_P.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblMaterial_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 200, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Material del producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo de producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del producto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Marca del producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Precio del producto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tamaño del producto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblTipo_P.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblTipo_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, 20));

        lblNombre_p.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblNombre_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, 20));

        lblMarca_P.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblMarca_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 20));

        lblPrecio_P.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblPrecio_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 200, 20));

        lblTamaño_P.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblTamaño_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, 20));

        txaMuestreo.setBackground(new java.awt.Color(255, 255, 255));
        txaMuestreo.setColumns(20);
        txaMuestreo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txaMuestreo.setForeground(new java.awt.Color(0, 0, 0));
        txaMuestreo.setRows(5);
        jScrollPane1.setViewportView(txaMuestreo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 890, 160));

        btnAlta.setBackground(new java.awt.Color(0, 51, 255));
        btnAlta.setForeground(new java.awt.Color(0, 0, 0));
        btnAlta.setText("Dar de alta ");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        btnAceptar3.setBackground(new java.awt.Color(102, 102, 255));
        btnAceptar3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptar3.setText("Atras");
        btnAceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 80, 20));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        
        TipoP=JOptionPane.showInputDialog(null,"Instroduzca el Tipo de producto");
        NombreP=JOptionPane.showInputDialog(null,"Instroduzca el Nombre del producto");
        MarcaP=JOptionPane.showInputDialog(null,"Instroduzca la marca del producto ");
        PrecioP=Integer.parseInt(JOptionPane.showInputDialog(null,"Instroduzca el precio del producto"));
        TamañoP=JOptionPane.showInputDialog(null,"Instroduzca el Tamaño del producto ");
        MaterialP=JOptionPane.showInputDialog(null,"Instroduzca el material del producto");
        
        lblNombre_p.setText(TipoP);
        lblMaterial_P.setText(MaterialP);
        lblMarca_P.setText(MarcaP);
        lblPrecio_P.setText(String.valueOf(PrecioP));
        lblTamaño_P.setText(TamañoP);
        lblTipo_P.setText(MaterialP);
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        objMysql.ConexionconSql(TipoP,MaterialP,MarcaP,PrecioP,TamañoP,MaterialP);
        datosSQL=objMysql.MostrarSQL();
        txaMuestreo.setText(datosSQL);
        TipoP=null;NombreP=null;MarcaP=null;PrecioP=0;TamañoP=null;TipoP=null;
        lblNombre_p.setText(TipoP);
        lblMaterial_P.setText(MaterialP);
        lblMarca_P.setText(MarcaP);
        lblPrecio_P.setText(String.valueOf(PrecioP));
        lblTamaño_P.setText(TamañoP);
        lblTipo_P.setText(MaterialP);
        
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnAceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar3ActionPerformed
        // TODO add your handling code here:
        frmSeleccion verfrmSeleccion = new frmSeleccion();
        verfrmSeleccion.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAceptar3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:}
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar3;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMarca_P;
    private javax.swing.JLabel lblMaterial_P;
    private javax.swing.JLabel lblNombre_p;
    private javax.swing.JLabel lblPrecio_P;
    private javax.swing.JLabel lblTamaño_P;
    private javax.swing.JLabel lblTipo_P;
    private javax.swing.JTextArea txaMuestreo;
    // End of variables declaration//GEN-END:variables
}
