
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */

public class frmOrdenamiento extends javax.swing.JFrame {
    static int aux,n;
    frmPrincipal datosordenar= new frmPrincipal();
     static String ord;
     int [] ordenarP;
    int [] ordenarE;
    /**
     * Creates new form frmOrdenamiento
     */
    
    public frmOrdenamiento() {
        initComponents();
        this.setLocationRelativeTo(null);
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        btnAceptar3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ordenamiento por existencia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Ordenamiento por  Precio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txaMostrar.setColumns(20);
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 190, 210));

        btnAceptar3.setBackground(new java.awt.Color(102, 102, 255));
        btnAceptar3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptar3.setText("Atras");
        btnAceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 80, 20));

        jButton3.setText("Ordenamiento de mayor a menor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jButton4.setText("Ordenamiento de menor a mayor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButton1.setText("Ordenamiento de mayor a menor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButton2.setText("Ordenamiento de menor a mayor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        
    }//GEN-LAST:event_btnAceptar3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String [] producto={"Toalla","Pastilla","Tampon","Parche"};
        
        int [] ordenarP={10,15,12,18};
        int [] ordenarE={datosordenar.ntoallas,datosordenar.npastilla,datosordenar.ntapones,datosordenar.nparches};
        
        
            txaMostrar.setText(null);
            
	for(int i=0;i<ordenarP.length-1;i++){	
	for(int j=i+1;j<ordenarP.length;j++){
	if (ordenarP[i]>ordenarP[j]){	
	aux=ordenarP[j];
        ord=producto[j];
	ordenarP[j]=ordenarP[i];
        producto[j]=producto[i];
	ordenarP[i]=aux;
        producto[i]=ord;
          
        }
        }
        }
        for (int i=3;i>=0;i--)
        {
          txaMostrar.append(producto[i]+"  precio: $ "+ordenarP[i]+"\n\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
        String [] producto={"Toalla","Pastilla","Tampon","Parche"};
        
        int [] ordenarP={10,15,12,18};
        int [] ordenarE={datosordenar.ntoallas,datosordenar.npastilla,datosordenar.ntapones,datosordenar.nparches};
        
        
            txaMostrar.setText(null);
          
	for(int i=0;i<ordenarP.length-1;i++){	
	for(int j=i+1;j<ordenarP.length;j++){
	if (ordenarP[i]>ordenarP[j]){	
	aux=ordenarP[j];
        ord=producto[j];
	ordenarP[j]=ordenarP[i];
        producto[j]=producto[i];
	ordenarP[i]=aux;
        producto[i]=ord;
          
        }
        }
        }
        for (int i=0;i<4;i++)
        {
          txaMostrar.append(producto[i]+"  precio: $ "+ordenarP[i]+"\n\n");
        }
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String [] producto={"Toalla","Pastilla","Tampon","Parche"};
        
        int [] ordenarP={10,15,12,18};
        int [] ordenarE={datosordenar.ntoallas,datosordenar.npastilla,datosordenar.ntapones,datosordenar.nparches};
        
        
            txaMostrar.setText(null);
            
	for(int i=0;i<ordenarE.length-1;i++){	
	for(int j=i+1;j<ordenarE.length;j++){
	if (ordenarE[i]>ordenarE[j]){	
	aux=ordenarE[j];
        ord=producto[j];
	ordenarE[j]=ordenarE[i];
        producto[j]=producto[i];
	ordenarE[i]=aux;
        producto[i]=ord;
          
        }
        }
        }
        for (int i=3;i>=0;i--)
        {
          txaMostrar.append("Existencia de "+producto[i]+"   :"+ordenarE[i]+"\n\n");
        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String [] producto={"Toalla","Pastilla","Tampon","Parche"};
        
        int [] ordenarP={10,15,12,18};
        int [] ordenarE={datosordenar.ntoallas,datosordenar.npastilla,datosordenar.ntapones,datosordenar.nparches};
        
        
            txaMostrar.setText(null);
          
	for(int i=0;i<ordenarE.length-1;i++){	
	for(int j=i+1;j<ordenarE.length;j++){
	if (ordenarE[i]>ordenarE[j]){	
	aux=ordenarE[j];
        ord=producto[j];
	ordenarE[j]=ordenarE[i];
        producto[j]=producto[i];
	ordenarE[i]=aux;
        producto[i]=ord;
          
        }
        }
        }
        for (int i=0;i<4;i++)
        {
          txaMostrar.append("Existencia de "+producto[i]+"  : "+ordenarE[i]+"\n\n");
        }
      
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrdenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaMostrar;
    // End of variables declaration//GEN-END:variables
}
