
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;                                                                                     
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import panamahitek.Arduino.PanamaHitek_Arduino;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */
public class frmPago extends javax.swing.JFrame {
    frmPrincipal datosprincipal=new frmPrincipal();
    metodosArduino objArduino= new metodosArduino();
    
public static float supago=0,cambio,TotalpagarM,totaldepositoM;
  
    int sig=0;


//public static int dismunuyendo=0;
    /**
     * Creates new form frmPago
     */
    public frmPago() {
        initComponents();
         lblTotal.setText(""+datosprincipal.pagoproducto);
         if (datosprincipal.compartimiento==1)
        {
            lblProducto.setText("Producto a pagar : Toalla");
        }
         if (datosprincipal.compartimiento==2)
        {
            lblProducto.setText("Producto a pagar : Pastilla");
        }
          if (datosprincipal.compartimiento==3)
        {
            lblProducto.setText("Producto a pagar : Tampon");
        }
           if (datosprincipal.compartimiento==4)
        {
            lblProducto.setText("Producto a pagar : Parche");
        }
        this.setLocationRelativeTo(null);
        
        lblTotal.setText(datosprincipal.pagoproducto+"");
        
       
       
       
      
       objArduino.inicioConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDinero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPagar = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lbl2p = new javax.swing.JLabel();
        lbl10p = new javax.swing.JLabel();
        lbl1p = new javax.swing.JLabel();
        lbl50c = new javax.swing.JLabel();
        lbl5p = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblProducto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDinero.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        lblDinero.setForeground(new java.awt.Color(204, 0, 204));
        lblDinero.setText("0.0");
        jPanel1.add(lblDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 60));

        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Su pago: $");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 290, 60));

        lblPagar.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        lblPagar.setForeground(new java.awt.Color(204, 0, 204));
        lblPagar.setText(" PAGAR");
        lblPagar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));
        lblPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagarMouseClicked(evt);
            }
        });
        jPanel1.add(lblPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 230, -1));

        lblTotal.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(204, 0, 204));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 270, 60));

        lbl2p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        lbl2p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2pMouseClicked(evt);
            }
        });
        jPanel1.add(lbl2p, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 140, 140));

        lbl10p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N
        lbl10p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10pMouseClicked(evt);
            }
        });
        jPanel1.add(lbl10p, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, 140));

        lbl1p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        lbl1p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1pMouseClicked(evt);
            }
        });
        jPanel1.add(lbl1p, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, 140));

        lbl50c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/50c.png"))); // NOI18N
        lbl50c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl50cMouseClicked(evt);
            }
        });
        jPanel1.add(lbl50c, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 140, 140));

        lbl5p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.png"))); // NOI18N
        lbl5p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5pMouseClicked(evt);
            }
        });
        jPanel1.add(lbl5p, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 140, 140));

        jLabel5.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Seleccione las monedas ha depositar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 530, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, 30));

        lblProducto.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(204, 0, 204));
        lblProducto.setText("Producto a pagar:");
        jPanel1.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 730, 60));

        jSeparator1.setForeground(new java.awt.Color(204, 0, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 770, 10));

        jLabel7.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Precio a pagar: $");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 460, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenPago.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        txtTiempo.setText("jTextField1");
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagarMouseClicked
        // TODO add your handling code here:
         TotalpagarM=Float.parseFloat(lblTotal.getText());
        totaldepositoM=Float.parseFloat(lblDinero.getText());
        float faltante=TotalpagarM-totaldepositoM;
        cambio=totaldepositoM-TotalpagarM;
        if (totaldepositoM<TotalpagarM)
        {
            JOptionPane.showMessageDialog(null,"Dinero insuficiente le faltan : $"+faltante);
           
        }
         if (totaldepositoM>=TotalpagarM&&datosprincipal.compartimiento==1)
        {
         JOptionPane.showMessageDialog(null,"Gracias por su preferencia.\nSu cambio es de :$"+cambio);
       
       //Metodo arduino para boton toallas
           objArduino.servoToallas();
           datosprincipal.ntoallas-=1;
           datosprincipal.ventatoalla+=1;
         supago=0;
         lblDinero.setText(""+0.0);
        
          //meotodo de arduino para detener comuncacion y evitar errores
        objArduino.detener(); 
        frmPrincipal verfrPrincipal= new frmPrincipal();
        this.hide();
        verfrPrincipal.setVisible(true);
        }
        
         else if(totaldepositoM>=TotalpagarM&&datosprincipal.compartimiento==2)
        {
         JOptionPane.showMessageDialog(null,"Gracias por su preferencia.\nSu cambio es de :$"+cambio);
       
         
         //Metodo arduino para boton pastillas
         objArduino.servoPastillas();
        datosprincipal.npastilla-=1;
        datosprincipal.ventaPastilla+=1;
         supago=0;
         lblDinero.setText(""+0.0);
         lblTotal.setText(""+datosprincipal.pastilla);
        
          //meotodo de arduino para detener comuncacion y evitar errores
        objArduino.detener(); 
        frmPrincipal verfrPrincipal= new frmPrincipal();
        this.hide();
        verfrPrincipal.setVisible(true);
        }
         else if (totaldepositoM>=TotalpagarM&&datosprincipal.compartimiento==3)
        {
         JOptionPane.showMessageDialog(null,"Gracias por su preferencia.\nSu cambio es de :$"+cambio);
       
         
         //Metodo arduino para tampones
         objArduino.servoTampones();
         datosprincipal.ntapones-=1;
         datosprincipal.ventaTampon+=1;
         supago=0;
         lblDinero.setText(""+0.0);
         lblTotal.setText(""+datosprincipal.tampon);
         
         
         //meotodo de arduino para detener comuncacion y evitar errores
        objArduino.detener(); 
        frmPrincipal verfrPrincipal= new frmPrincipal();
        this.hide();
        verfrPrincipal.setVisible(true);
        }
         else  if (totaldepositoM>=TotalpagarM&&datosprincipal.compartimiento==4)
        {
         JOptionPane.showMessageDialog(null,"Gracias por su preferencia.\nSu cambio es de :$"+cambio);
       datosprincipal.ventaparche+=1;
        datosprincipal.nparches-=1;
         //metodo arduino para boton parche
         objArduino.servoParche();
         supago=0;
         lblDinero.setText(""+0.0);
         lblTotal.setText(""+datosprincipal.parche);
         
  
          //meotodo de arduino para detener comuncacion y evitar errores
        objArduino.detener(); 
        frmPrincipal verfrPrincipal= new frmPrincipal();
        this.hide();
        verfrPrincipal.setVisible(true);
        }
         
       
    }//GEN-LAST:event_lblPagarMouseClicked

    private void lbl50cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl50cMouseClicked
        // TODO add your handling code here:
        supago+=.5;
        lblDinero.setText(""+supago);
        
    }//GEN-LAST:event_lbl50cMouseClicked

    private void lbl1pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1pMouseClicked
        // TODO add your handling code here:
        supago+=1;
        lblDinero.setText(""+supago);
    }//GEN-LAST:event_lbl1pMouseClicked

    private void lbl2pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2pMouseClicked
        // TODO add your handling code here:
        supago+=2;
        lblDinero.setText(""+supago);
    }//GEN-LAST:event_lbl2pMouseClicked

    private void lbl5pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5pMouseClicked
        // TODO add your handling code here:
        supago+=5;
        lblDinero.setText(""+supago);
    }//GEN-LAST:event_lbl5pMouseClicked

    private void lbl10pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10pMouseClicked
        // TODO add your handling code here:
         supago+=10;
        lblDinero.setText(""+supago);
    }//GEN-LAST:event_lbl10pMouseClicked

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
           
           supago=0;
           lblDinero.setText("0.0");
           //Metodo para cerrar conexion con arduino y evitar problemas de comunicacion
           objArduino.detener();
          frmPrincipal verfrmPrincipal = new frmPrincipal();
          verfrmPrincipal.setVisible(true );
          this.hide();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl10p;
    private javax.swing.JLabel lbl1p;
    private javax.swing.JLabel lbl2p;
    private javax.swing.JLabel lbl50c;
    private javax.swing.JLabel lbl5p;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
