
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */
public class frmPrincipal extends javax.swing.JFrame {
    public  static float toalla=10,tampon=12,pastilla=15,parche=18,pagoproducto=0,totaltoallaE=0,totaltamponE=0,totalpastillaE=0,totalparcheE=0;;
public  static   int  ntoallas=15,npastilla=15,ntapones=15,nparches=15,compartimiento=0,ventatoalla=0,ventaparche=0,ventaTampon=0,ventaPastilla=0;
        
    
DefaultCategoryDataset datosG= new DefaultCategoryDataset();
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultCategoryDataset datosG= new DefaultCategoryDataset();
        datosG.setValue(ntoallas,"Compartimeinto1","Toallas");
        datosG.setValue(npastilla,"compartimeinto2","Pastillas");
        datosG.setValue(nparches,"compartimeinto3","Parches");
        datosG.setValue(ntapones,"compartimeinto4","Tampones");
        
       JFreeChart graficobarras3d = ChartFactory.createBarChart3D(
             "Inventario del dispensador", //Nombregrafico
             "Productos del dispensador",//nombredebarras
              " Cantidad de produtos",//nombrenumeracion
              datosG,//datosdlgrafico
              PlotOrientation.VERTICAL,//orientacion
              true,//Letyendadebarrasindividuales por color
              true,//herramientas
              false //urlgrafico
               
       );
       
       ChartPanel panel= new ChartPanel(graficobarras3d);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(550,460));//medidas
       
       jpanelGrafico.setLayout(new BorderLayout());
       jpanelGrafico.add(panel,BorderLayout.NORTH);
       jpanelGrafico.validate();
       
       
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpanelGrafico = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnParche = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        btnToalla = new javax.swing.JButton();
        btnPastilla = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnTampon = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelGrafico.setBackground(new java.awt.Color(255, 255, 255));
        jpanelGrafico.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 2, new java.awt.Color(255, 0, 255)));

        javax.swing.GroupLayout jpanelGraficoLayout = new javax.swing.GroupLayout(jpanelGrafico);
        jpanelGrafico.setLayout(jpanelGraficoLayout);
        jpanelGraficoLayout.setHorizontalGroup(
            jpanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jpanelGraficoLayout.setVerticalGroup(
            jpanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jPanel2.add(jpanelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 650, 480));

        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("DE PRODUCTOS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 220, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("PARA LA SALUD DE LA MUJER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 450, 40));

        btnParche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parche2.png"))); // NOI18N
        btnParche.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        btnParche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcheActionPerformed(evt);
            }
        });
        jPanel2.add(btnParche, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 190, 120));

        btnAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adm.png"))); // NOI18N
        btnAdministrar.setText("jButton1");
        btnAdministrar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 190, 120));

        btnToalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/toallafemenina2.png"))); // NOI18N
        btnToalla.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        btnToalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToallaActionPerformed(evt);
            }
        });
        jPanel2.add(btnToalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 190, 120));

        btnPastilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pastillas2.png"))); // NOI18N
        btnPastilla.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        btnPastilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastillaActionPerformed(evt);
            }
        });
        jPanel2.add(btnPastilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 190, 110));

        jLabel4.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("SISTEMA DISPENSADOR ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 350, -1));

        btnTampon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tampon2.png"))); // NOI18N
        btnTampon.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        btnTampon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamponActionPerformed(evt);
            }
        });
        jPanel2.add(btnTampon, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 190, 120));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPrincipal.png"))); // NOI18N
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        txtTiempo.setText("jTextField1");
        jPanel2.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToallaActionPerformed
        // TODO add your handling code here:
      
       totaltoallaE=ventatoalla*toalla;
      
       pagoproducto=toalla; 
        compartimiento=1;
        datosG.setValue(ntoallas,"Compartimeinto1","Toallas");
        datosG.setValue(npastilla,"compartimeinto2","Pastillas");
        datosG.setValue(nparches,"compartimeinto3","Parches");
        datosG.setValue(ntapones,"compartimeinto4","Tampones");
        
       JFreeChart graficobarras3d = ChartFactory.createBarChart3D(
             "Inventario del dispensador", //Nombregrafico
             "Productos del dispensador",//nombredebarras
              " Cantidad de produtos",//nombrenumeracion
              datosG,//datosdlgrafico
              PlotOrientation.VERTICAL,//orientacion
              true,//Letyendadebarrasindividuales por color
              true,//herramientas
              false //urlgrafico
               
       );
       
       ChartPanel panel= new ChartPanel(graficobarras3d);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(550,460));//medidas
       
       jpanelGrafico.setLayout(new BorderLayout());
       jpanelGrafico.add(panel,BorderLayout.NORTH);
       jpanelGrafico.validate();
       
       frmPago verfrmPago = new frmPago();
       verfrmPago.setVisible(true);
       this.hide();  
    }//GEN-LAST:event_btnToallaActionPerformed

    private void btnPastillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastillaActionPerformed
        // TODO add your handling code here:
       
      
       totalpastillaE=ventaPastilla*pastilla;
       pagoproducto=pastilla; 
        compartimiento=2;
        datosG.setValue(ntoallas,"Compartimeinto1","Toallas");
        datosG.setValue(npastilla,"compartimeinto2","Pastillas");
        datosG.setValue(nparches,"compartimeinto3","Parches");
        datosG.setValue(ntapones,"compartimeinto4","Tampones");
        
       JFreeChart graficobarras3d = ChartFactory.createBarChart3D(
             "Inventario del dispensador", //Nombregrafico
             "Productos del dispensador",//nombredebarras
              " Cantidad de produtos",//nombrenumeracion
              datosG,//datosdlgrafico
              PlotOrientation.VERTICAL,//orientacion
              true,//Letyendadebarrasindividuales por color
              true,//herramientas
              false //urlgrafico
               
       );
       
       ChartPanel panel= new ChartPanel(graficobarras3d);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(550,460));//medidas
       
       jpanelGrafico.setLayout(new BorderLayout());
       jpanelGrafico.add(panel,BorderLayout.NORTH);
       jpanelGrafico.validate();
       
        frmPago verfrmPago = new frmPago();
       verfrmPago.setVisible(true);
       this.hide(); 
        
    }//GEN-LAST:event_btnPastillaActionPerformed

    private void btnTamponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamponActionPerformed
        // TODO add your handling code here:
        
      
       totaltamponE=ventaTampon*tampon;
     
       pagoproducto=tampon; 
        compartimiento=3;
        datosG.setValue(ntoallas,"Compartimeinto1","Toallas");
        datosG.setValue(npastilla,"compartimeinto2","Pastillas");
        datosG.setValue(nparches,"compartimeinto3","Parches");
        datosG.setValue(ntapones,"compartimeinto4","Tampones");
        
       JFreeChart graficobarras3d = ChartFactory.createBarChart3D(
             "Inventario del dispensador", //Nombregrafico
             "Productos del dispensador",//nombredebarras
              " Cantidad de produtos",//nombrenumeracion
              datosG,//datosdlgrafico
              PlotOrientation.VERTICAL,//orientacion
              true,//Letyendadebarrasindividuales por color
              true,//herramientas
              false //urlgrafico
               
       );
       
       ChartPanel panel= new ChartPanel(graficobarras3d);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(550,460));//medidas
       
       jpanelGrafico.setLayout(new BorderLayout());
       jpanelGrafico.add(panel,BorderLayout.NORTH);
       jpanelGrafico.validate();
       
        frmPago verfrmPago = new frmPago();
       verfrmPago.setVisible(true);
       this.hide(); 
        
    }//GEN-LAST:event_btnTamponActionPerformed

    private void btnParcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcheActionPerformed
        // TODO add your handling code here:
       
       totalparcheE=ventaparche*parche;
       pagoproducto=parche; 
        compartimiento=4;
        datosG.setValue(ntoallas,"Compartimeinto1","Toallas");
        datosG.setValue(npastilla,"compartimeinto2","Pastillas");
        datosG.setValue(nparches,"compartimeinto3","Parches");
        datosG.setValue(ntapones,"compartimeinto4","Tampones");
        
       JFreeChart graficobarras3d = ChartFactory.createBarChart3D(
             "Inventario del dispensador", //Nombregrafico
             "Productos del dispensador",//nombredebarras
              " Cantidad de produtos",//nombrenumeracion
              datosG,//datosdlgrafico
              PlotOrientation.VERTICAL,//orientacion
              true,//Letyendadebarrasindividuales por color
              true,//herramientas
              false //urlgrafico
               
       );
       
       ChartPanel panel= new ChartPanel(graficobarras3d);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(550,460));//medidas
       
       jpanelGrafico.setLayout(new BorderLayout());
       jpanelGrafico.add(panel,BorderLayout.NORTH);
       jpanelGrafico.validate();
       
        frmPago verfrmPago = new frmPago();
       verfrmPago.setVisible(true);
       this.hide(); 
        
    }//GEN-LAST:event_btnParcheActionPerformed

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        // TODO add your handling code here:
        frmIniciodeSesion verfrmIniciodeSesion= new frmIniciodeSesion();
        verfrmIniciodeSesion.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnAdministrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnParche;
    private javax.swing.JButton btnPastilla;
    private javax.swing.JButton btnTampon;
    private javax.swing.JButton btnToalla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpanelGrafico;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
