
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kenor
 */
public class frmSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form frmSeleccion
     */
    public frmSeleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
       
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblVentas = new javax.swing.JLabel();
        lblAlta = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFondoAdmon = new javax.swing.JLabel();
        lblFondoAdmon1 = new javax.swing.JLabel();
        lblFondoAdmon2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir1.setBackground(new java.awt.Color(204, 0, 255));
        btnSalir1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalir1.setText("Regresar al inicio");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 200, 20));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 70, 20));

        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
        });
        jPanel1.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 900, 191));

        lblAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAltaMouseClicked(evt);
            }
        });
        jPanel1.add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 900, 197));

        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventarioMouseClicked(evt);
            }
        });
        jPanel1.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 197));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 100)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inventario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 160));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ventas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 620, 160));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alta de productos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 620, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconoalta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 180, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconoventas.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 180, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoInventario.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 180, 180));

        lblFondoAdmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo apartado 2.png"))); // NOI18N
        jPanel1.add(lblFondoAdmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 198, 900, 197));

        lblFondoAdmon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo apartado 3.png"))); // NOI18N
        jPanel1.add(lblFondoAdmon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 397, 900, 191));

        lblFondoAdmon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo apartado 1.png"))); // NOI18N
        jPanel1.add(lblFondoAdmon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 197));

        lblFondo.setText("  ");
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseClicked
        // TODO add your handling code here:
        frmAdmon verfrmAdmon = new frmAdmon();
        verfrmAdmon.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lblInventarioMouseClicked

    private void lblAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaMouseClicked
        // TODO add your handling code here:
        frmInventario verfrmInventario = new frmInventario();
        verfrmInventario.setVisible(true);
        this.hide();
        /*
        frmAltadeProductos verfrmAltadeProductos = new frmAltadeProductos();
        verfrmAltadeProductos.setVisible(true);
        this.hide();
        */
    }//GEN-LAST:event_lblAltaMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        // TODO add your handling code here:frmAdmon verfrmAdmon = new frmAdmon();
        frmAltaP verfrmAltaP = new frmAltaP();
        verfrmAltaP.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_lblVentasMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:}
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        frmPrincipal verfrmPrincipal= new frmPrincipal();
        verfrmPrincipal.show();
        this.hide();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoAdmon;
    private javax.swing.JLabel lblFondoAdmon1;
    private javax.swing.JLabel lblFondoAdmon2;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables
}
